### ISSUE TITLE
Only getting 'No results received'

### ISSUE THREAD

**Issue by stigkj** [goadapp/goad#15] opened 2016-03-17 21:51 UTC
When I'm running goad I only get 'No results received' after some seconds. For example using this:

```
goad -c 5 -r eu-west-1 -n 5 -u https://goad.io/
```

I'm running on OS X 10.10 with go version go1.5.3 darwin/amd64. The git hash that I compiled from is 431bb06. Do you need any more information?

Ooh...I have gone through some iterations for finding the correct permissions in IAM.

**Comment by sdsykes** [comment] 2016-03-26 17:25
Something broke, investigating. The downloadable binaries should still work ok though.

**Comment by sdsykes** [comment] 2016-03-27 19:13
It seems it's likely that there was an old version of the lambda function on your AWS. Please check in your AWS console and delete any goad function that is there. (We are adding a feature to support versioned lambda functions soon.)
With a clean AWS, and a clean checkout of goad (note you'll want to use Go 1.6 now) then it should work.

Closing, but get back if you still have a problem.

**Comment by adimarco** [comment] 2016-03-31 16:55
I'm still seeing this behavior with the latest 64-bit Linux binaries.  I'm running it from a box that has AdministratorAccess IAM permissions and no Lambda functions defined in any region.

**Comment by sdsykes** [comment] 2016-04-01 08:35
Likely because we didn't update the binaries like we should have, we will do that shortly.

**Comment by webteknik** [comment] 2016-04-01 13:41
Hi,
I am having the same problem. I first tried with the binary from releases, then I tried with go get ..., but I still get "No results recevied" even after deleting the lambda functions.
```
goad -version
1.1.0.pre

aws --region eu-west-1 lambda list-functions
{
    "Functions": [
        {
            "Version": "$LATEST",
            "CodeSha256": "/gjkXSwnHmLHXd8fA72WcLgRvlboWhVvU0Frw+i2src=",
            "FunctionName": "goad",
            "MemorySize": 1536,
            "CodeSize": 3007895,
            "FunctionArn": "arn:aws:lambda:eu-west-1:726671005420:function:goad",
            "Handler": "index.handler",
            "Role": "arn:aws:iam::726671005420:role/goad-lambda-role",
            "Timeout": 300,
            "LastModified": "2016-04-01T13:13:58.667+0000",
            "Runtime": "nodejs",
            "Description": ""
        }
    ]
}

```

**Comment by sdsykes** [comment] 2016-04-03 20:33
I just tested the latest and it's working. I also made some new binaries so please try those, check under Releases. Let us know if it doesn't work.

**Comment by stigkj** [comment] 2016-04-03 22:24
I tried with the new binaries, but still does not work. I also tried to delete the lambda function first, but no luck. I've listed the version and function below. Do you need any more information from me to reproduce?

```
> goad -version
1.1.0.pre

> aws --region eu-west-1 lambda list-functions
{
    "Functions": [
        {
            "Version": "$LATEST",
            "CodeSha256": "FmT+OdVtRRdaZYaVMihiqBsta6ft1pJHwZnybikpAcQ=",
            "FunctionName": "goad",
            "MemorySize": 1536,
            "CodeSize": 2994063,
            "FunctionArn": "arn:aws:lambda:eu-west-1:879238767243:function:goad",
            "Handler": "index.handler",
            "Role": "arn:aws:iam::879238767243:role/goad-lambda-role",
            "Timeout": 300,
            "LastModified": "2016-04-03T22:18:01.535+0000",
            "Runtime": "nodejs",
            "Description": ""
        }
    ]
}
```

**Comment by webteknik** [comment] 2016-04-04 13:34
When I try, I see that requests keep coming to my web server even after goad cli exits and prints "No results received". So is it possible that lambda function does not end or deliver its results properly to the cli? I am not familiar with AWS or node.js but there is a warning in the AWS documentation:

> To properly terminate your Lambda function execution, you must call context.succeed(), context.fail(), or context.done() method. If you don't, either your Lambda function will continue to run until the Node.js event queue is empty, or your Lambda function times out.
http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

It seems that context.done is only called when an error occured
```
    child = execFile(event.file, event.args, function(error) {
        context.done(error, "Process complete!");
    });
```
https://github.com/goadapp/goad/blob/6f1e0d2417da8329cacc73ff139d2987bbfaa43c/data/lambda/index.js#L4-L6

Can this cause the error? If it is irrelevant, then sorry for noise.

**Comment by michaeljs1990** [comment] 2016-04-07 23:49
I'm getting this as well after pulling down the latest binary

**Comment by danielmotaleite** [comment] 2016-04-22 16:37
also the same thing here.
tried go 1.5 and go 1.6 and both v1.1.0.pre and gopher-gala, always with the same result (actually go 1.5 + v1.1.0.pre crashed)

i see the goad being created in the lambda and the invocation count increasing, but in the end all we got is "No results received".

I'm using a standar debian micro instance in aws, so should be easy to replicate

**Comment by jcxplorer** [comment] 2016-04-22 17:00
Good to know that the lambda is being invoked. Are you able to see any logs
from that invocation? If so, could you share them with us?

**Comment by danielmotaleite** [comment] 2016-04-22 17:23
well, clicking in the lambda "View logs in CloudWatch" i go the a non-existent "/aws/lambda/goad" log group... i created it, but still no logs.

In the command line, we see no error or messages

**Comment by danielmotaleite** [comment] 2016-04-22 18:21
correction, i found that goad creates the SQS queue, then remove it later

**Comment by danielmotaleite** [comment] 2016-04-22 19:03
Trying to use the goad-lambda i get this:

```
 ./data/lambda/goad-lambda  -c 5 -n 100  -r eu-west-1   -u https://www.example.com/
Using a timeout of 15s
Using a reporting frequency of 15s
Will spawn 5 workers making 100 requests to https://www.example.com/
Spawning workersâ¦..... done.
Waiting for resultsâ¦
100.00% done (100 requests out of 100)MissingRegion: could not find region configuration

Yayð  - 100 requests completed
```
but i do have a region defined...

**Comment by jcxplorer** [comment] 2016-04-22 19:53
@danielmotaleite that error is most likely coming from the fact that you didn't specify the region for the SQS queue (https://github.com/goadapp/goad/blob/master/lambda/lambda.go#L42).

Could you check for lambda logs once again? They sometimes take a few minutes to show up...

You could also try creating an SQS queue by hand, and specifying the SQS queue region with that `-q` flag and also the queue URL with `-s`. After that, the SQS queue should have some messages inside. It would be helpful to know if the messages are getting written to the queue correctly :)

**Comment by danielmotaleite** [comment] 2016-04-22 23:41
This seems to work, i get some messages to the goad-12345 queue:

`$ data/lambda/goad-lambda  -c 100 -n 10000  -r eu-west-1  -q eu-west-1   -s https://sqs.eu-west-1.amazonaws.com/315417893466/goad-12345   -f 5s -u https://www.example.com/`

For the logs, i created the "/aws/lambda/goad"  log group, but i have no log stream and have no idea what name it should have... either way, it is still empty 

OK, after several tests, i found the source of the problem... the queue is created, but without permissions. If after the queue creation i quickly add permissions for everyone, the output show up in to the running cli output

So there is some bug in the queue creation or the default sqs permissions changed and right now the lambda can not access the sqs queue

**Comment by jcxplorer** [comment] 2016-04-23 18:17
@danielmotaleite thanks a lot for looking into this. It'll definitely help in reproducing and getting it fixed!

I should have some time next week to look into this.

**Comment by danielmotaleite** [comment] 2016-04-28 17:18
today  i manage to test a little more and i notice that the goad role is created, but the goad-lambda-role-policy policy is not.

I just created a new policy with this info:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:SendMessage"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:sqs:*:*:goad-*"
        },
        {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:logs:*:*:*"
        }
    ]
}
```
And then add the "goad-lambda-role" role to the entity tab of the "goad-lambda-role-policy" policy... test it and now everything works fine... fine :)

So it is working for you because you already have the policy created and on new users it goad doesn't work because it fails to create the policy for unknown reasons. it is also why there is no logs, no permissions are set to log anything

**Comment by sdsykes** [comment] 2016-05-01 12:47
Thanks again. Am trying to reproduce and fix this now.

**Closed** 2016-05-01 22:19 UTC

**Comment by jeberly** [comment] 2016-06-12 01:44
I am still seeing "No results received" problem and I pulled and compiled the latest code with https://github.com/goadapp/goad/commit/c20378384cfb1c253aa1beca2a5f4c7499a3ef31

**Comment by danielmotaleite** [comment] 2016-06-13 19:31
remove any goad policy in aws, you probably have a old, incorrect policy there...
also check for any stale sqs

**Comment by SophisticaSean** [comment] 2016-07-28 23:59
@danielmotaleite thank you so much. without your help and your policy comment I probably never would have had goad working correctly. This is when i built goad from source too. Someone should add a pull request to the README so people know they have to set up the policy and goad-lambda-role before goad will work.
