### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by aaroncai-myob** [goadapp/goad#167] opened 2017-08-21 00:45 UTC
Failed to build from source 
go get github.com/goadapp/goad

`github.com/goadapp/goad/infrastructure/docker
../../go/src/github.com/goadapp/goad/infrastructure/docker/docker.go:245: undefined: infrastructure.Asset
 github.com/goadapp/goad/infrastructure/aws
../../go/src/github.com/goadapp/goad/infrastructure/aws/aws.go:95: undefined: infrastructure.Asset`

**Comment by cwaltken-edrans** [comment] 2017-08-22 14:08
This is a duplicate of #32.
Goad builds fine with `make build` or `make install`.

**Closed** 2017-08-22 15:11 UTC
Labels: wontfix
